# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
sudo: false
dist: trusty
cache: packages
latex: false
fortran: false

jobs:
  include:
  - r: devel
  - os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
#    before_cache:
#    - Rscript -e 'remotes::install_cran("pkgdown")'
#    deploy:
#      provider: script
#      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
#      skip_cleanup: true
  - r: 3.4
  - r: 3.3
  - r: 3.2
    warnings_are_errors: false
